# Generated by Django 3.1.3 on 2021-01-02 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('------', '------'), ('bodega', 'BODEGA'), ('terreno', 'TERRENO')], default='------', max_length=50)),
                ('transaction_type', models.CharField(choices=[('------', '------'), ('RNT', 'RENTA'), ('VNT', 'VENTA')], default='------', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('------', '------'), ('GDL', 'Guadalajara'), ('ZAP', 'Zapopan'), ('TLJ', 'Tlajomulco'), ('TNL', 'Tonala'), ('CHA', 'Chapala'), ('STL', 'El Salto')], default='------', max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_published', models.BooleanField(default=True)),
                ('office', models.BooleanField(default=False)),
                ('dock', models.BooleanField(default=False)),
                ('industrial_park', models.BooleanField(default=False)),
                ('vigilancia', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
